HTTP/1.1 200 
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
Content-Type: application/json
Transfer-Encoding: chunked
Date: Wed, 16 Jul 2025 06:09:48 GMT
Connection: close

{"message":"Tipos de mascota encontrados.","status":200,"data":[{"idTipoMascota":1,"nombre":"Perro"},{"idTipoMascota":2,"nombre":"Gato"}]}