HTTP/1.1 200 
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
Content-Type: application/json
Transfer-Encoding: chunked
Date: Wed, 16 Jul 2025 06:12:41 GMT
Connection: close

{"message":"Tipo de mascota encontrado.","status":200,"data":{"idTipoMascota":2,"nombre":"Gato"}}