# ENDPOINTS DE CARACTERISTICA DE MASCOTA

GET http://127.0.0.1:5000/car_mascotas_routes/get_car_mascotas
#####

POST http://127.0.0.1:5000/car_mascotas_routes/get_car_mascota
Content-Type: application/json

{
    "id_caracteristica": 5,
    "id_mascota": 4
}
#####