# ENDPOINTS DE CARACTERISTICA DE MASCOTA

GET http://127.0.0.1:8080/car_mascota_routes/get_caracteristicas_mascotas
#####

POST http://127.0.0.1:8080/car_mascota_routes/get_caracteristica_mascota
Content-Type: application/json

{
    "id_caracteristica": 2,
    "id_mascota": 2
}
#####