# ENDPOINTS DE CARACTERISTICA COMPLEMENTARIA

GET http://127.0.0.1:8080/car_complementaria_routes/get_caracteristicas_complementarias
#####

POST http://127.0.0.1:8080/car_complementaria_routes/get_caracteristica_complementaria
Content-Type: application/json

{
    "id_caracteristica_complementaria": 1
}
#####