HTTP/1.1 200 OK
Server: Werkzeug/3.1.3 Python/3.12.5
Date: Sun, 13 Jul 2025 19:42:20 GMT
Content-Type: application/json
Content-Length: 170
Access-Control-Allow-Origin: localhost
Connection: close

{
  "data": {
    "id_caracteristica": 5,
    "id_mascota": 4,
    "valor": "Blanco y negro"
  },
  "message": "Caracteristica de mascota encontrada.",
  "status": 200
}
