HTTP/1.1 200 OK
Server: Werkzeug/3.1.3 Python/3.12.5
Date: Sun, 13 Jul 2025 19:39:35 GMT
Content-Type: application/json
Content-Length: 7082
Access-Control-Allow-Origin: localhost
Connection: close

{
  "data": [
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.60",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2022-01-15",
      "foto": "url1.jpg",
      "id_mascota": 1,
      "id_raza": 1,
      "id_tipo_mascota": 1,
      "nombre": "Toby",
      "peso": "20.50",
      "sexo": "M"
    },
    {
      "adoptado": true,
      "discapacidad": false,
      "estatura": "0.35",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2021-11-23",
      "foto": "url2.jpg",
      "id_mascota": 2,
      "id_raza": 3,
      "id_tipo_mascota": 2,
      "nombre": "Luna",
      "peso": "10.00",
      "sexo": "F"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.55",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2023-03-10",
      "foto": "url3.jpg",
      "id_mascota": 3,
      "id_raza": 2,
      "id_tipo_mascota": 1,
      "nombre": "Max",
      "peso": "25.00",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.30",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2020-09-18",
      "foto": "url4.jpg",
      "id_mascota": 4,
      "id_raza": 4,
      "id_tipo_mascota": 2,
      "nombre": "Mila",
      "peso": "5.50",
      "sexo": "F"
    },
    {
      "adoptado": true,
      "discapacidad": false,
      "estatura": "0.25",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2021-02-07",
      "foto": "url5.jpg",
      "id_mascota": 5,
      "id_raza": 7,
      "id_tipo_mascota": 3,
      "nombre": "Coco",
      "peso": "2.30",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": true,
      "estatura": "0.70",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2019-05-14",
      "foto": "url6.jpg",
      "id_mascota": 6,
      "id_raza": 5,
      "id_tipo_mascota": 1,
      "nombre": "Rocky",
      "peso": "27.00",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.40",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2022-12-20",
      "foto": "url7.jpg",
      "id_mascota": 7,
      "id_raza": 4,
      "id_tipo_mascota": 2,
      "nombre": "Nala",
      "peso": "6.00",
      "sexo": "F"
    },
    {
      "adoptado": true,
      "discapacidad": false,
      "estatura": "0.45",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2020-01-05",
      "foto": "url8.jpg",
      "id_mascota": 8,
      "id_raza": 3,
      "id_tipo_mascota": 2,
      "nombre": "Simba",
      "peso": "7.80",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.15",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2023-04-10",
      "foto": "url9.jpg",
      "id_mascota": 9,
      "id_raza": 6,
      "id_tipo_mascota": 6,
      "nombre": "Daisy",
      "peso": "0.80",
      "sexo": "F"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.50",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2021-06-11",
      "foto": "url10.jpg",
      "id_mascota": 10,
      "id_raza": 1,
      "id_tipo_mascota": 1,
      "nombre": "Thor",
      "peso": "21.00",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.30",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2022-08-12",
      "foto": "url11.jpg",
      "id_mascota": 11,
      "id_raza": 4,
      "id_tipo_mascota": 2,
      "nombre": "Bella",
      "peso": "4.30",
      "sexo": "F"
    },
    {
      "adoptado": true,
      "discapacidad": false,
      "estatura": "0.10",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2020-12-01",
      "foto": "url12.jpg",
      "id_mascota": 12,
      "id_raza": 8,
      "id_tipo_mascota": 4,
      "nombre": "Leo",
      "peso": "0.30",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.55",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2019-03-05",
      "foto": "url13.jpg",
      "id_mascota": 13,
      "id_raza": 2,
      "id_tipo_mascota": 1,
      "nombre": "Milo",
      "peso": "12.00",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.30",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2022-05-23",
      "foto": "url14.jpg",
      "id_mascota": 14,
      "id_raza": 7,
      "id_tipo_mascota": 3,
      "nombre": "Lola",
      "peso": "5.00",
      "sexo": "F"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.20",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2023-01-30",
      "foto": "url15.jpg",
      "id_mascota": 15,
      "id_raza": 10,
      "id_tipo_mascota": 5,
      "nombre": "Zeus",
      "peso": "1.00",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": true,
      "estatura": "0.45",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2021-09-07",
      "foto": "url16.jpg",
      "id_mascota": 16,
      "id_raza": 3,
      "id_tipo_mascota": 2,
      "nombre": "Nina",
      "peso": "8.00",
      "sexo": "F"
    },
    {
      "adoptado": true,
      "discapacidad": false,
      "estatura": "0.12",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2022-06-16",
      "foto": "url17.jpg",
      "id_mascota": 17,
      "id_raza": 8,
      "id_tipo_mascota": 4,
      "nombre": "Chispa",
      "peso": "0.60",
      "sexo": "F"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.33",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2020-10-20",
      "foto": "url18.jpg",
      "id_mascota": 18,
      "id_raza": 6,
      "id_tipo_mascota": 1,
      "nombre": "Tommy",
      "peso": "6.40",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.16",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2023-02-11",
      "foto": "url19.jpg",
      "id_mascota": 19,
      "id_raza": 6,
      "id_tipo_mascota": 6,
      "nombre": "Pepa",
      "peso": "0.50",
      "sexo": "F"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.60",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2022-07-25",
      "foto": "url20.jpg",
      "id_mascota": 20,
      "id_raza": 1,
      "id_tipo_mascota": 1,
      "nombre": "Kira",
      "peso": "23.00",
      "sexo": "F"
    }
  ],
  "message": "Mascotas encontradas.",
  "status": 200
}
