HTTP/1.1 200 OK
Server: Werkzeug/3.1.3 Python/3.12.5
Date: Sun, 20 Jul 2025 20:20:58 GMT
Content-Type: application/json
Content-Length: 155
Access-Control-Allow-Origin: http://localhost:4200
Vary: Origin
Connection: close

{
  "data": {
    "id_tipo_mascota": 2,
    "nombre": "Gato",
    "origen": "albergue1"
  },
  "message": "Tipo de mascota encontrado.",
  "status": 200
}
