HTTP/1.1 200 OK
Server: Werkzeug/3.1.3 Python/3.12.5
Date: Sun, 20 Jul 2025 20:29:07 GMT
Content-Type: application/json
Content-Length: 472
Access-Control-Allow-Origin: http://localhost:4200
Vary: Origin
Connection: close

{
  "data": {
    "adoptado": 1,
    "discapacidad": 0,
    "estatura": "0.30",
    "fec_ingreso": "2025-07-18T07:03:34.000Z",
    "fec_nacimiento": "2020-07-15T05:00:00.000Z",
    "foto": "https://images.pexels.com/photos/2173872/pexels-photo-2173872.jpeg",
    "id_mascota": 2,
    "id_raza": 2,
    "id_tipo_mascota": 2,
    "nombre": "Princesa",
    "origen": "albergue3",
    "peso": "4.50",
    "sexo": "F"
  },
  "message": "Mascota encontrada.",
  "status": 200
}
