HTTP/1.1 200 OK
Server: Werkzeug/3.1.3 Python/3.12.5
Date: Sun, 20 Jul 2025 04:57:40 GMT
Content-Type: application/json
Content-Length: 945
Access-Control-Allow-Origin: localhost
Connection: close

{
  "data": [
    {
      "id_caracteristica": 1,
      "nombre": "Energ\u00eda",
      "unidad_medida": "niveles"
    },
    {
      "id_caracteristica": 2,
      "nombre": "Sociabilidad",
      "unidad_medida": "niveles"
    },
    {
      "id_caracteristica": 3,
      "nombre": "Entrenado",
      "unidad_medida": "bool"
    },
    {
      "id_caracteristica": 4,
      "nombre": "Vacunado",
      "unidad_medida": "bool"
    },
    {
      "id_caracteristica": 5,
      "nombre": "Color",
      "unidad_medida": "texto"
    },
    {
      "idCaracteristica": 1,
      "nombre": "Sociabilidad",
      "unidadMedida": "media"
    },
    {
      "idCaracteristica": 2,
      "nombre": "Apto ni\u00f1os",
      "unidadMedida": "s\u00ed/no"
    },
    {
      "idCaracteristica": 3,
      "nombre": "Nivel energ\u00eda",
      "unidadMedida": "alta"
    }
  ],
  "message": "Caracter\u00edsticas complementarias encontradas.",
  "status": 200
}
