HTTP/1.1 200 OK
Server: Werkzeug/3.1.3 Python/3.12.5
Date: Sun, 20 Jul 2025 17:18:08 GMT
Content-Type: application/json
Content-Length: 1206
Access-Control-Allow-Origin: http://localhost:4200
Vary: Origin
Connection: close

{
  "data": [
    {
      "id_tipo_mascota": 1,
      "nombre": "Perro",
      "origen": "albergue1"
    },
    {
      "id_tipo_mascota": 2,
      "nombre": "Gato",
      "origen": "albergue1"
    },
    {
      "id_tipo_mascota": 3,
      "nombre": "Conejo",
      "origen": "albergue1"
    },
    {
      "id_tipo_mascota": 4,
      "nombre": "Ave",
      "origen": "albergue1"
    },
    {
      "id_tipo_mascota": 5,
      "nombre": "Tortuga",
      "origen": "albergue1"
    },
    {
      "id_tipo_mascota": 6,
      "nombre": "Hamster",
      "origen": "albergue1"
    },
    {
      "id_tipo_mascota": 7,
      "nombre": "Pez",
      "origen": "albergue1"
    },
    {
      "idTipoMascota": 2,
      "nombre": "Gato",
      "origen": "albergue2"
    },
    {
      "idTipoMascota": 1,
      "nombre": "Perro",
      "origen": "albergue2"
    },
    {
      "id_tipo_mascota": 3,
      "nombre": "Conejo",
      "origen": "albergue3"
    },
    {
      "id_tipo_mascota": 2,
      "nombre": "Gato",
      "origen": "albergue3"
    },
    {
      "id_tipo_mascota": 1,
      "nombre": "Perro",
      "origen": "albergue3"
    }
  ],
  "message": "Tipos de mascotas encontrados.",
  "status": 200
}
