HTTP/1.1 200 OK
Server: Werkzeug/3.1.3 Python/3.12.5
Date: Sun, 20 Jul 2025 05:00:37 GMT
Content-Type: application/json
Content-Length: 1256
Access-Control-Allow-Origin: localhost
Connection: close

{
  "data": [
    {
      "id_caracteristica": 1,
      "id_mascota": 1,
      "valor": "Alta"
    },
    {
      "id_caracteristica": 2,
      "id_mascota": 1,
      "valor": "Media"
    },
    {
      "id_caracteristica": 3,
      "id_mascota": 2,
      "valor": "true"
    },
    {
      "id_caracteristica": 4,
      "id_mascota": 3,
      "valor": "true"
    },
    {
      "id_caracteristica": 5,
      "id_mascota": 4,
      "valor": "Blanco y negro"
    },
    {
      "id_caracteristica": 1,
      "id_mascota": 5,
      "valor": "Baja"
    },
    {
      "id_caracteristica": 3,
      "id_mascota": 6,
      "valor": "false"
    },
    {
      "id_caracteristica": 2,
      "id_mascota": 7,
      "valor": "Alta"
    },
    {
      "id_caracteristica": 5,
      "id_mascota": 8,
      "valor": "Naranja"
    },
    {
      "id_caracteristica": 1,
      "id_mascota": 9,
      "valor": "Media"
    },
    {
      "idCaracteristica": 1,
      "idMascota": 2,
      "valor": "Media"
    },
    {
      "idCaracteristica": 2,
      "idMascota": 2,
      "valor": "S\u00ed"
    },
    {
      "idCaracteristica": 3,
      "idMascota": 1,
      "valor": "Alta"
    }
  ],
  "message": "Caracter\u00edsticas de mascotas encontradas.",
  "status": 200
}
