HTTP/1.1 200 OK
Server: Werkzeug/3.1.3 Python/3.12.5
Date: Sun, 20 Jul 2025 17:22:42 GMT
Content-Type: application/json
Content-Length: 1406
Access-Control-Allow-Origin: http://localhost:4200
Vary: Origin
Connection: close

{
  "data": [
    {
      "id_raza": 1,
      "nombre": "Labrador",
      "origen": "albergue1"
    },
    {
      "id_raza": 2,
      "nombre": "Golden Retriever",
      "origen": "albergue1"
    },
    {
      "id_raza": 3,
      "nombre": "Persa",
      "origen": "albergue1"
    },
    {
      "id_raza": 4,
      "nombre": "Siames",
      "origen": "albergue1"
    },
    {
      "id_raza": 5,
      "nombre": "Husky",
      "origen": "albergue1"
    },
    {
      "id_raza": 6,
      "nombre": "Bulldog",
      "origen": "albergue1"
    },
    {
      "id_raza": 7,
      "nombre": "Angora",
      "origen": "albergue1"
    },
    {
      "id_raza": 8,
      "nombre": "Canario",
      "origen": "albergue1"
    },
    {
      "id_raza": 9,
      "nombre": "Pomerania",
      "origen": "albergue1"
    },
    {
      "id_raza": 10,
      "nombre": "Betta",
      "origen": "albergue1"
    },
    {
      "idRaza": 1,
      "nombre": "Labrador",
      "origen": "albergue2"
    },
    {
      "idRaza": 2,
      "nombre": "Persa",
      "origen": "albergue2"
    },
    {
      "id_raza": 3,
      "nombre": "Holland Lop",
      "origen": "albergue3"
    },
    {
      "id_raza": 1,
      "nombre": "Labrador Retriever",
      "origen": "albergue3"
    },
    {
      "id_raza": 2,
      "nombre": "Persa",
      "origen": "albergue3"
    }
  ],
  "message": "Razas encontradas.",
  "status": 200
}
