HTTP/1.1 200 OK
Server: Werkzeug/3.1.3 Python/3.12.5
Date: Sun, 20 Jul 2025 19:49:13 GMT
Content-Type: application/json
Content-Length: 11190
Access-Control-Allow-Origin: http://localhost:4200
Vary: Origin
Connection: close

{
  "data": [
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.60",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2022-01-15",
      "foto": "https://images.pexels.com/photos/179221/pexels-photo-179221.jpeg",
      "id_mascota": 1,
      "id_raza": 1,
      "id_tipo_mascota": 1,
      "nombre": "Toby",
      "origen": "albergue1",
      "peso": "20.50",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.55",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2023-03-10",
      "foto": "https://images.pexels.com/photos/17407385/pexels-photo-17407385.jpeg",
      "id_mascota": 3,
      "id_raza": 2,
      "id_tipo_mascota": 1,
      "nombre": "Max",
      "origen": "albergue1",
      "peso": "25.00",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": true,
      "estatura": "0.70",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2019-05-14",
      "foto": "https://images.pexels.com/photos/28683174/pexels-photo-28683174.jpeg",
      "id_mascota": 6,
      "id_raza": 5,
      "id_tipo_mascota": 1,
      "nombre": "Rocky",
      "origen": "albergue1",
      "peso": "27.00",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.50",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2021-06-11",
      "foto": "https://images.pexels.com/photos/19131363/pexels-photo-19131363.jpeg",
      "id_mascota": 10,
      "id_raza": 1,
      "id_tipo_mascota": 1,
      "nombre": "Thor",
      "origen": "albergue1",
      "peso": "21.00",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.55",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2019-03-05",
      "foto": "https://images.pexels.com/photos/40986/dog-bulldog-white-tongue-40986.jpeg",
      "id_mascota": 13,
      "id_raza": 2,
      "id_tipo_mascota": 1,
      "nombre": "Milo",
      "origen": "albergue1",
      "peso": "12.00",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.33",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2020-10-20",
      "foto": "https://images.pexels.com/photos/13394871/pexels-photo-13394871.jpeg",
      "id_mascota": 18,
      "id_raza": 6,
      "id_tipo_mascota": 1,
      "nombre": "Tommy",
      "origen": "albergue1",
      "peso": "6.40",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.60",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2022-07-25",
      "foto": "https://images.pexels.com/photos/7483187/pexels-photo-7483187.jpeg",
      "id_mascota": 20,
      "id_raza": 1,
      "id_tipo_mascota": 1,
      "nombre": "Kira",
      "origen": "albergue1",
      "peso": "23.00",
      "sexo": "F"
    },
    {
      "adoptado": true,
      "discapacidad": false,
      "estatura": "0.35",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2021-11-23",
      "foto": "https://images.pexels.com/photos/179237/pexels-photo-179237.jpeg",
      "id_mascota": 2,
      "id_raza": 3,
      "id_tipo_mascota": 2,
      "nombre": "Luna",
      "origen": "albergue1",
      "peso": "10.00",
      "sexo": "F"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.30",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2020-09-18",
      "foto": "https://images.pexels.com/photos/667228/pexels-photo-667228.jpeg",
      "id_mascota": 4,
      "id_raza": 4,
      "id_tipo_mascota": 2,
      "nombre": "Mila",
      "origen": "albergue1",
      "peso": "5.50",
      "sexo": "F"
    },
    {
      "adoptado": true,
      "discapacidad": false,
      "estatura": "0.25",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2021-02-07",
      "foto": "https://images.pexels.com/photos/7408291/pexels-photo-7408291.jpeg",
      "id_mascota": 5,
      "id_raza": 7,
      "id_tipo_mascota": 3,
      "nombre": "Coco",
      "origen": "albergue1",
      "peso": "2.30",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.40",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2022-12-20",
      "foto": "https://images.pexels.com/photos/3652805/pexels-photo-3652805.jpeg",
      "id_mascota": 7,
      "id_raza": 4,
      "id_tipo_mascota": 2,
      "nombre": "Nala",
      "origen": "albergue1",
      "peso": "6.00",
      "sexo": "F"
    },
    {
      "adoptado": true,
      "discapacidad": false,
      "estatura": "0.45",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2020-01-05",
      "foto": "https://images.pexels.com/photos/4790612/pexels-photo-4790612.jpeg",
      "id_mascota": 8,
      "id_raza": 3,
      "id_tipo_mascota": 2,
      "nombre": "Simba",
      "origen": "albergue1",
      "peso": "7.80",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.30",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2022-08-12",
      "foto": "https://images.pexels.com/photos/14440674/pexels-photo-14440674.jpeg",
      "id_mascota": 11,
      "id_raza": 4,
      "id_tipo_mascota": 2,
      "nombre": "Bella",
      "origen": "albergue1",
      "peso": "4.30",
      "sexo": "F"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.30",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2022-05-23",
      "foto": "https://images.pexels.com/photos/33012107/pexels-photo-33012107.jpeg",
      "id_mascota": 14,
      "id_raza": 7,
      "id_tipo_mascota": 3,
      "nombre": "Lola",
      "origen": "albergue1",
      "peso": "5.00",
      "sexo": "F"
    },
    {
      "adoptado": false,
      "discapacidad": true,
      "estatura": "0.45",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2021-09-07",
      "foto": "https://images.pexels.com/photos/32949175/pexels-photo-32949175.jpeg",
      "id_mascota": 16,
      "id_raza": 3,
      "id_tipo_mascota": 2,
      "nombre": "Nina",
      "origen": "albergue1",
      "peso": "8.00",
      "sexo": "F"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.15",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2023-04-10",
      "foto": "https://images.pexels.com/photos/15316904/pexels-photo-15316904.jpeg",
      "id_mascota": 9,
      "id_raza": 6,
      "id_tipo_mascota": 6,
      "nombre": "Daisy",
      "origen": "albergue1",
      "peso": "0.80",
      "sexo": "F"
    },
    {
      "adoptado": true,
      "discapacidad": false,
      "estatura": "0.10",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2020-12-01",
      "foto": "https://images.pexels.com/photos/1617293/pexels-photo-1617293.jpeg",
      "id_mascota": 12,
      "id_raza": 8,
      "id_tipo_mascota": 4,
      "nombre": "Leo",
      "origen": "albergue1",
      "peso": "0.30",
      "sexo": "M"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.20",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2023-01-30",
      "foto": "https://images.pexels.com/photos/28257370/pexels-photo-28257370.jpeg",
      "id_mascota": 15,
      "id_raza": 10,
      "id_tipo_mascota": 5,
      "nombre": "Zeus",
      "origen": "albergue1",
      "peso": "1.00",
      "sexo": "M"
    },
    {
      "adoptado": true,
      "discapacidad": false,
      "estatura": "0.12",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2022-06-16",
      "foto": "https://images.pexels.com/photos/10502515/pexels-photo-10502515.jpeg",
      "id_mascota": 17,
      "id_raza": 8,
      "id_tipo_mascota": 4,
      "nombre": "Chispa",
      "origen": "albergue1",
      "peso": "0.60",
      "sexo": "F"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": "0.16",
      "fec_ingreso": "2025-07-13T13:28:43.623345-05:00",
      "fec_nacimiento": "2023-02-11",
      "foto": "https://wallpapers.com/images/hd/listening-hamster-meme-g6oqtkrr5g9z6d4a.jpg",
      "id_mascota": 19,
      "id_raza": 6,
      "id_tipo_mascota": 6,
      "nombre": "Pepa",
      "origen": "albergue1",
      "peso": "0.50",
      "sexo": "F"
    },
    {
      "adoptado": false,
      "discapacidad": false,
      "estatura": 0.55,
      "fecIngreso": "2025-07-16T00:35:49.615-05:00",
      "fecNacimiento": "2018-05-10",
      "foto": "https://images.pexels.com/photos/7176277/pexels-photo-7176277.jpeg",
      "idMascota": 1,
      "idRaza": 1,
      "idTipoMascota": 1,
      "nombre": "Rocky",
      "origen": "albergue2",
      "peso": 22.4,
      "sexo": "M"
    },
    {
      "adoptado": true,
      "discapacidad": false,
      "estatura": 0.25,
      "fecIngreso": "2025-07-16T00:35:49.622-05:00",
      "fecNacimiento": "2020-08-25",
      "foto": "https://images.pexels.com/photos/2646483/pexels-photo-2646483.jpeg",
      "idMascota": 2,
      "idRaza": 2,
      "idTipoMascota": 2,
      "nombre": "Luna",
      "origen": "albergue2",
      "peso": 3.5,
      "sexo": "F"
    },
    {
      "adoptado": 0,
      "discapacidad": 0,
      "estatura": "0.55",
      "fec_ingreso": "2025-07-18T07:03:34.000Z",
      "fec_nacimiento": "2022-03-01T05:00:00.000Z",
      "foto": "https://images.pexels.com/photos/27680249/pexels-photo-27680249.jpeg",
      "id_mascota": 1,
      "id_raza": 1,
      "id_tipo_mascota": 1,
      "nombre": "Venom",
      "origen": "albergue3",
      "peso": "20.00",
      "sexo": "M"
    },
    {
      "adoptado": 1,
      "discapacidad": 0,
      "estatura": "0.30",
      "fec_ingreso": "2025-07-18T07:03:34.000Z",
      "fec_nacimiento": "2020-07-15T05:00:00.000Z",
      "foto": "https://images.pexels.com/photos/2173872/pexels-photo-2173872.jpeg",
      "id_mascota": 2,
      "id_raza": 2,
      "id_tipo_mascota": 2,
      "nombre": "Princesa",
      "origen": "albergue3",
      "peso": "4.50",
      "sexo": "F"
    },
    {
      "adoptado": 0,
      "discapacidad": 1,
      "estatura": "0.25",
      "fec_ingreso": "2025-07-18T07:03:34.000Z",
      "fec_nacimiento": "2023-01-20T05:00:00.000Z",
      "foto": "https://th.bing.com/th/id/R.89a312b3f51aa0b70e815e1f38fe72d6?rik=%2b15O5LE0hSF5%2bg&riu=http%3a%2f%2fwww.baltana.com%2ffiles%2fwallpapers-6%2fCute-White-Baby-Rabbit-Wallpaper-19291.jpg&ehk=3Jk6lEoryVdb3iNbRYk8Qffpeb5UowHCvQLeT4uxKs8%3d&risl=&pid=ImgRaw&r=0",
      "id_mascota": 3,
      "id_raza": 3,
      "id_tipo_mascota": 3,
      "nombre": "Copito",
      "origen": "albergue3",
      "peso": "1.30",
      "sexo": "M"
    }
  ],
  "message": "Mascotas encontradas.",
  "status": 200
}
